'use client';

import Link from 'next/link';
import { useParams } from 'next/navigation';
import { useEffect, useState } from 'react';
import { Bar, BarChart, Cell, Line, LineChart, Pie, PieChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts';

const api = typeof window !== 'undefined' ? `${window.location.protocol}//${window.location.hostname}:9000/api/v1` : process.env.NEXT_PUBLIC_API_URL || 'http://localhost:9000/api/v1';
const colours = ['#22d3ee', '#818cf8', '#34d399', '#fbbf24', '#fb7185', '#a78bfa'];
type Machine = { id: string; hostname: string; user: string | null; ip: string | null; status: string; last_heartbeat_at: string | null };
type Activity = { id: string; application: string; window_title: string | null; username: string | null; started_at: string; duration_seconds: number };
type Analytics = { total_seconds: number; applications: { application: string; seconds: number; percentage: number }[]; timeline: { start: string; seconds: number; is_work_hour: boolean }[] };
type Metric = { collected_at: string; cpu_percent: number | null; cpu_frequency_mhz: number | null; cpu_frequency_max_mhz: number | null; cpu_model: string | null; cpu_logical_count: number | null; cpu_physical_count: number | null; ram_percent: number | null; ram_used_mb: number | null; ram_total_mb: number | null; gpu_percent: number | null; gpu_memory_used_mb: number | null; gpu_memory_total_mb: number | null; gpu_name: string | null; uptime_seconds: number | null };
type Telemetry = { latest: Metric | null; history: Metric[] };
const duration = (seconds: number) => seconds >= 3600 ? `${Math.floor(seconds / 3600)}h ${Math.round(seconds % 3600 / 60)}min` : `${Math.round(seconds / 60)} min`;
const date = (value: string | null) => value ? new Date(value).toLocaleString('pt-BR') : 'Nunca';
const metric = (numberValue: number | null | undefined, suffix = '') => numberValue === null || numberValue === undefined ? 'Indisponível' : `${numberValue.toFixed(1)}${suffix}`;
const memory = (megabytes: number | null | undefined) => megabytes === null || megabytes === undefined ? 'Indisponível' : `${(megabytes / 1024).toFixed(1)} GB`;
const uptime = (seconds: number | null | undefined) => seconds === null || seconds === undefined ? 'Indisponível' : `${Math.floor(seconds / 86400)}d ${Math.floor(seconds % 86400 / 3600)}h`;

export default function Detail() {
  const { id } = useParams<{ id: string }>();
  const [machine, setMachine] = useState<Machine | null>(null); const [activity, setActivity] = useState<Activity[]>([]); const [analytics, setAnalytics] = useState<Analytics | null>(null); const [telemetry, setTelemetry] = useState<Telemetry | null>(null);
  const [appFilter, setAppFilter] = useState(''); const [hours, setHours] = useState(24); const [name, setName] = useState(''); const [editing, setEditing] = useState(false); const [error, setError] = useState('');
  const headers = () => ({ Authorization: `Bearer ${localStorage.getItem('ati_token')}` });
  async function load() {
    const query = `application=${encodeURIComponent(appFilter)}&hours=${hours}`;
    const results = await Promise.all([fetch(`${api}/machines`, { headers: headers() }), fetch(`${api}/machines/${id}/activity?${query}`, { headers: headers() }), fetch(`${api}/machines/${id}/analytics?${query}`, { headers: headers() }), fetch(`${api}/machines/${id}/telemetry`, { headers: headers() })]);
    if (results.some(response => response.status === 401)) { localStorage.clear(); window.location.href = '/login'; return; }
    if (results.some(response => !response.ok)) throw Error('Não foi possível carregar os detalhes da máquina.');
    const found = (await results[0].json()).find((item: Machine) => item.id === id) || null; setMachine(found); setName(found?.hostname || ''); setActivity(await results[1].json()); setAnalytics(await results[2].json()); setTelemetry(await results[3].json());
  }
  useEffect(() => { load().catch(requestError => setError(requestError.message)); }, [id, appFilter, hours]);
  async function save() { const response = await fetch(`${api}/machines/${id}`, { method: 'PATCH', headers: { ...headers(), 'Content-Type': 'application/json' }, body: JSON.stringify({ hostname: name.trim() }) }); if (!response.ok) { setError('Não foi possível alterar o hostname.'); return; } setEditing(false); load().catch(requestError => setError(requestError.message)); }
  if (error) return <div className="card text-amber-300">{error}</div>; if (!machine || !analytics || !telemetry) return <p className="text-slate-400">Carregando detalhes...</p>;
  const latest = telemetry.latest; const timeline = analytics.timeline.map(item => ({ ...item, label: new Date(item.start).toLocaleTimeString('pt-BR', { hour: '2-digit', minute: '2-digit' }), minutes: Math.round(item.seconds / 60) })); const metricHistory = telemetry.history.map(item => ({ ...item, label: new Date(item.collected_at).toLocaleTimeString('pt-BR', { hour: '2-digit', minute: '2-digit' }) }));
  return <>
    <div className="mb-6 flex items-center justify-between gap-4"><div><Link href="/machines" className="text-sm text-cyan-300">Voltar para máquinas</Link>{editing ? <div className="mt-3 flex gap-2"><input className="rounded border border-slate-700 bg-slate-900 px-3 py-2" value={name} onChange={event => setName(event.target.value)} /><button className="rounded bg-cyan-400 px-3 text-sm font-medium text-slate-950" onClick={save}>Salvar</button><button className="text-sm text-slate-400" onClick={() => setEditing(false)}>Cancelar</button></div> : <h2 className="mt-3 text-2xl font-semibold">{machine.hostname}</h2>}</div><div className="flex gap-3"><button className="text-sm text-cyan-300" onClick={() => setEditing(true)}>Alterar hostname</button><span className="rounded-full border border-slate-700 px-3 py-1 text-sm">{machine.status}</span></div></div>
    <section className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4"><div className="card"><p className="text-sm text-slate-400">CPU</p><p className="mt-2 font-medium">{metric(latest?.cpu_percent, '%')}</p><p className="text-xs text-slate-500">{latest?.cpu_model || 'Modelo indisponível'}</p></div><div className="card"><p className="text-sm text-slate-400">RAM</p><p className="mt-2 font-medium">{metric(latest?.ram_percent, '%')}</p><p className="text-xs text-slate-500">{memory(latest?.ram_used_mb)} de {memory(latest?.ram_total_mb)}</p></div><div className="card"><p className="text-sm text-slate-400">GPU</p><p className="mt-2 font-medium">{metric(latest?.gpu_percent, '%')}</p><p className="text-xs text-slate-500">{latest?.gpu_name || 'GPU não reportada'}</p></div><div className="card"><p className="text-sm text-slate-400">Uptime</p><p className="mt-2 font-medium">{uptime(latest?.uptime_seconds)}</p><p className="text-xs text-slate-500">Atualizado {date(latest?.collected_at || null)}</p></div></section>
    <section className="card mt-4"><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><div><p className="text-xs text-slate-500">Frequência CPU</p><p className="mt-1 font-medium">{metric(latest?.cpu_frequency_mhz, ' MHz')} / {metric(latest?.cpu_frequency_max_mhz, ' MHz')}</p></div><div><p className="text-xs text-slate-500">Núcleos</p><p className="mt-1 font-medium">{latest?.cpu_physical_count ?? '—'} físicos · {latest?.cpu_logical_count ?? '—'} lógicos</p></div><div><p className="text-xs text-slate-500">Memória da GPU</p><p className="mt-1 font-medium">{memory(latest?.gpu_memory_used_mb)} / {memory(latest?.gpu_memory_total_mb)}</p></div><div><p className="text-xs text-slate-500">Usuário e IP</p><p className="mt-1 font-medium">{machine.user || '—'} · {machine.ip || '—'}</p></div></div></section>
    <section className="card mt-4"><h3 className="font-medium">Histórico de recursos</h3><p className="mt-1 text-sm text-slate-400">Snapshots enviados pelo agente, aproximadamente a cada minuto.</p><div className="mt-4 h-56"><ResponsiveContainer width="100%" height="100%"><LineChart data={metricHistory}><XAxis dataKey="label" interval="preserveStartEnd" tick={{ fill: '#94a3b8', fontSize: 11 }} /><YAxis unit="%" domain={[0, 100]} tick={{ fill: '#94a3b8', fontSize: 11 }} /><Tooltip formatter={(chartValue: number) => `${chartValue.toFixed(1)}%`} /><Line type="monotone" dataKey="cpu_percent" name="CPU" stroke="#22d3ee" dot={false} /><Line type="monotone" dataKey="ram_percent" name="RAM" stroke="#fbbf24" dot={false} /><Line type="monotone" dataKey="gpu_percent" name="GPU" stroke="#a78bfa" dot={false} /></LineChart></ResponsiveContainer></div></section>
    <section className="mt-6 grid gap-6 lg:grid-cols-2"><div className="card"><h3 className="font-medium">Uso por aplicação</h3><p className="mt-1 text-sm text-slate-400">Total no período: {duration(analytics.total_seconds)}</p><div className="mt-4 h-64"><ResponsiveContainer width="100%" height="100%"><PieChart><Pie data={analytics.applications.slice(0, 6)} dataKey="seconds" nameKey="application" innerRadius={60} outerRadius={96}>{analytics.applications.slice(0, 6).map((item, index) => <Cell key={item.application} fill={colours[index]} />)}</Pie><Tooltip formatter={(chartValue: number) => duration(chartValue)} /></PieChart></ResponsiveContainer></div><div className="space-y-2">{analytics.applications.map((item, index) => <div className="flex justify-between text-sm" key={item.application}><span><i className="mr-2 inline-block h-2 w-2 rounded-full" style={{ backgroundColor: colours[index % colours.length] }} />{item.application}</span><span className="text-slate-300">{duration(item.seconds)} · {item.percentage}%</span></div>)}</div></div><div className="card"><h3 className="font-medium">Interação por hora</h3><p className="mt-1 text-sm text-slate-400">Período analisado: últimas {hours} horas.</p><div className="mt-4 h-64"><ResponsiveContainer width="100%" height="100%"><BarChart data={timeline}><XAxis dataKey="label" interval={2} tick={{ fill: '#94a3b8', fontSize: 11 }} /><YAxis unit=" min" tick={{ fill: '#94a3b8', fontSize: 11 }} /><Tooltip formatter={(chartValue: number) => `${chartValue} min`} /><Bar dataKey="minutes" name="Interação">{timeline.map((item, index) => <Cell key={index} fill={item.is_work_hour ? (item.minutes ? '#22d3ee' : '#334155') : '#1e293b'} />)}</Bar></BarChart></ResponsiveContainer></div></div></section>
    <section className="card mt-6"><div className="mb-4 flex flex-wrap items-end gap-3"><label className="text-sm">Aplicação<input className="mt-1 block rounded border border-slate-700 bg-slate-900 px-3 py-2" placeholder="Ex.: opera" value={appFilter} onChange={event => setAppFilter(event.target.value)} /></label><label className="text-sm">Período<select className="mt-1 block rounded border border-slate-700 bg-slate-900 px-3 py-2" value={hours} onChange={event => setHours(Number(event.target.value))}><option value={8}>8 horas</option><option value={24}>24 horas</option><option value={168}>7 dias</option><option value={720}>30 dias</option></select></label><div className="ml-auto text-sm text-slate-300">{appFilter ? `Total de ${appFilter}: ${duration(analytics.total_seconds)}` : `Total rastreado: ${duration(analytics.total_seconds)}`}</div></div><div className="mb-4 flex justify-between"><h3 className="text-lg font-medium">Logs de utilização</h3><span className="text-sm text-slate-400">{activity.length} registros</span></div><div className="overflow-auto"><table className="w-full min-w-[680px] text-left text-sm"><thead className="text-slate-400"><tr><th>Aplicação</th><th>Janela</th><th>Usuário</th><th>Início</th><th>Duração</th></tr></thead><tbody>{activity.map(item => <tr className="border-t border-slate-800" key={item.id}><td className="py-3 font-medium">{item.application}</td><td className="max-w-xs truncate">{item.window_title || '—'}</td><td>{item.username || '—'}</td><td>{date(item.started_at)}</td><td>{duration(item.duration_seconds)}</td></tr>)}</tbody></table></div></section>
  </>;
}